"use client"

import { format } from "date-fns"
import { useDashboard } from "@/components/linear/dashboard-context"
import { useAI } from "@/components/linear/ai-context"
import { DateRange } from "react-day-picker"

// Define types for data passed to the report
interface ReportTemplateProps {
    data: any
    dateRange: DateRange | undefined
}

export function ReportTemplate({ data, dateRange }: ReportTemplateProps) {
    const { insights } = useAI()
    const { properties, selectedProperty } = useDashboard()

    // Find property name
    const propertyName = properties.find(p => p.id === selectedProperty)?.name || "Analytics Report"

    if (!data) return null
    const { metrics, trafficSources } = data

    // Helper to format duration
    const formatDuration = (seconds: number) => {
        const m = Math.floor(seconds / 60)
        const s = Math.floor(seconds % 60)
        return `${m}m ${s}s`
    }

    return (
        <div id="print-report-template" className="bg-white text-black p-10 max-w-[800px] mx-auto min-h-[1100px]" style={{ fontFamily: 'Times New Roman, serif' }}>
            {/* Header */}
            <div className="border-b-2 border-black pb-4 mb-8 flex justify-between items-end">
                <div>
                    <h1 className="text-3xl font-bold uppercase tracking-wide">Analytics Report</h1>
                    <p className="text-sm mt-1 text-gray-600">Generated by HelpfulAnalytics</p>
                </div>
                <div className="text-right">
                    <h2 className="text-xl font-semibold">{propertyName}</h2>
                    <p className="text-sm">
                        {dateRange?.from ? format(dateRange.from, "MMM dd, yyyy") : "Start"} - {dateRange?.to ? format(dateRange.to, "MMM dd, yyyy") : "End"}
                    </p>
                </div>
            </div>

            {/* AI Executive Summary */}
            {insights.length > 0 && (
                <div className="mb-8 p-4 bg-gray-50 border border-gray-200 rounded">
                    <h3 className="text-lg font-bold mb-2 border-b border-gray-300 pb-1">Executive Summary</h3>
                    {insights.map((insight, i) => (
                        <div key={i} className="mb-2">
                            <span className="font-semibold text-sm uppercase text-gray-700">{insight.type}:</span>
                            <p className="text-base italic leading-relaxed">{insight.description}</p>
                        </div>
                    ))}
                </div>
            )}

            {/* Key Metrics Table */}
            <section className="mb-8">
                <h3 className="text-lg font-bold mb-4 border-b border-gray-300 pb-1">Key Performance Indicators</h3>
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-gray-100 border-b border-black">
                            <th className="p-2 font-bold">Metric</th>
                            <th className="p-2 font-bold text-right">Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr className="border-b border-gray-300">
                            <td className="p-2">Total Users</td>
                            <td className="p-2 text-right font-mono">{metrics.users.toLocaleString()}</td>
                        </tr>
                        <tr className="border-b border-gray-300">
                            <td className="p-2">Sessions</td>
                            <td className="p-2 text-right font-mono">{metrics.sessions.toLocaleString()}</td>
                        </tr>
                        <tr className="border-b border-gray-300">
                            <td className="p-2">Avg. Session Duration</td>
                            <td className="p-2 text-right font-mono">{formatDuration(metrics.avgSessionDuration)}</td>
                        </tr>
                        <tr className="border-b border-gray-300">
                            <td className="p-2">Bounce Rate</td>
                            <td className="p-2 text-right font-mono">{(metrics.bounceRate * 100).toFixed(1)}%</td>
                        </tr>
                        <tr className="border-b border-gray-300">
                            <td className="p-2">Engagement Rate</td>
                            <td className="p-2 text-right font-mono">{(metrics.engagementRate * 100).toFixed(1)}%</td>
                        </tr>
                    </tbody>
                </table>
            </section>

            {/* Traffic Sources Table */}
            <section className="mb-8">
                <h3 className="text-lg font-bold mb-4 border-b border-gray-300 pb-1">Traffic Sources</h3>
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-gray-100 border-b border-black">
                            <th className="p-2 font-bold">Channel</th>
                            <th className="p-2 font-bold text-right">Sessions</th>
                            <th className="p-2 font-bold text-right">% Traffic</th>
                        </tr>
                    </thead>
                    <tbody>
                        {trafficSources?.map((source: any, i: number) => (
                            <tr key={i} className="border-b border-gray-300">
                                <td className="p-2">{source.source}</td>
                                <td className="p-2 text-right font-mono">{source.sessions.toLocaleString()}</td>
                                <td className="p-2 text-right font-mono">{source.percentage.toFixed(1)}%</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </section>

            {/* Top Pages Table */}
            {data.topPages && (
                <section className="mb-8">
                    <h3 className="text-lg font-bold mb-4 border-b border-gray-300 pb-1">Top Viewed Pages</h3>
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-gray-100 border-b border-black">
                                <th className="p-2 font-bold">Page Title</th>
                                <th className="p-2 font-bold text-right">Views</th>
                                <th className="p-2 font-bold text-right">% Views</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.topPages.map((page: any, i: number) => (
                                <tr key={i} className="border-b border-gray-300">
                                    <td className="p-2 truncate max-w-[300px]">{page.title}</td>
                                    <td className="p-2 text-right font-mono">{page.views.toLocaleString()}</td>
                                    <td className="p-2 text-right font-mono">{page.percentage.toFixed(1)}%</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </section>
            )}

            {/* Top Countries Table */}
            {data.topCountries && (
                <section className="mb-8">
                    <h3 className="text-lg font-bold mb-4 border-b border-gray-300 pb-1">Top Locations</h3>
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-gray-100 border-b border-black">
                                <th className="p-2 font-bold">Country</th>
                                <th className="p-2 font-bold text-right">Sessions</th>
                                <th className="p-2 font-bold text-right">% Traffic</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.topCountries.map((country: any, i: number) => (
                                <tr key={i} className="border-b border-gray-300">
                                    <td className="p-2">{country.country}</td>
                                    <td className="p-2 text-right font-mono">{country.sessions.toLocaleString()}</td>
                                    <td className="p-2 text-right font-mono">{country.percentage.toFixed(1)}%</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </section>
            )}

            {/* Footer */}
            <div className="mt-12 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
                <p>Confidential Analytics Report • Generated by HelpfulAnalytics • {format(new Date(), "PPpp")}</p>
            </div>
        </div>
    )
}
