import { NextResponse } from 'next/server';
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";
import { Resend } from 'resend';
import { db } from "@/lib/firebase-admin"

export async function POST(req: Request) {
    const resendKey = process.env.RESEND_API_KEY
    if (!resendKey) {
        console.error('RESEND_API_KEY is not configured')
        return NextResponse.json({ error: 'Email service is not configured. Add RESEND_API_KEY to your environment.' }, { status: 500 });
    }

    const resend = new Resend(resendKey);

    const session = await getServerSession(authOptions);

    if (!session?.user?.email) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    try {
        const formData = await req.formData();
        const file = formData.get('file') as Blob;

        if (!file) {
            return NextResponse.json({ error: 'No file provided' }, { status: 400 });
        }

        const buffer = Buffer.from(await file.arrayBuffer());
        const filename = (file as any).name || 'analytics-report.pdf';

        let from = 'Analytics Report <no-reply@helpfulanalytics.com>'
        let replyTo: string | undefined

        try {
            const settingsDoc = await db.collection("admin_settings").doc("global").get()
            const settings = settingsDoc.exists ? settingsDoc.data() : {}
            if (settings?.reportFromEmail) {
                from = String(settings.reportFromEmail)
            }
            replyTo =
                (settings?.supportEmail && String(settings.supportEmail)) ||
                (settings?.adminReplyToEmail && String(settings.adminReplyToEmail)) ||
                undefined
        } catch (settingsErr) {
            console.warn('Could not load admin_settings, using default from address:', settingsErr)
        }

        console.log(`Sending report email: from="${from}" to="${session.user.email}" file="${filename}" size=${buffer.length}`)

        const data = await resend.emails.send({
            from,
            to: session.user.email,
            subject: `Your ${filename.endsWith('.csv') ? 'CSV Data' : 'PDF Report'} - Helpful Analytics`,
            html: `
                <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #f59e0b;">Analytics Insight Ready</h2>
                    <p>Hello,</p>
                    <p>Attached is your requested analytics dashboard export (<b>${filename}</b>).</p>
                    <p>This report includes the metrics and AI-powered insights generated from your dashboard.</p>
                    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
                    <footer style="font-size: 12px; color: #666;">
                        Generated by Helpful Analytics Engine.
                    </footer>
                </div>
            `,
            attachments: [
                {
                    filename,
                    content: buffer,
                },
            ],
            ...(replyTo ? { replyTo } : {}),
        });

        if (data.error) {
            console.error('Resend API Error:', JSON.stringify(data.error));
            const msg = data.error.message || 'Failed to send email'
            // Surface actionable info
            if (msg.includes('not verified') || msg.includes('not a verified')) {
                return NextResponse.json({ error: `The sender domain is not verified in Resend. Current from: "${from}". Verify your domain at resend.com/domains or change reportFromEmail in admin settings.` }, { status: 400 });
            }
            return NextResponse.json({ error: msg }, { status: 400 });
        }

        return NextResponse.json({ success: true });
    } catch (error: any) {
        console.error('Email Route exception:', error?.message || error);
        return NextResponse.json({ error: error?.message || 'Internal Server Error' }, { status: 500 });
    }
}
