import { NextResponse } from 'next/server';
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";
import { Resend } from 'resend';

// Use dummy key for build/dev if missing, but logging warning in dev
const resendKey = process.env.RESEND_API_KEY || "re_dummy_key_for_build"
const resend = new Resend(resendKey);

export async function POST(req: Request) {
    const session = await getServerSession(authOptions);

    if (!session?.user?.email) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    try {
        const formData = await req.formData();
        const file = formData.get('file') as Blob;

        if (!file) {
            return NextResponse.json({ error: 'No file provided' }, { status: 400 });
        }

        const buffer = Buffer.from(await file.arrayBuffer());
        const filename = (file as any).name || 'analytics-report.pdf';

        const data = await resend.emails.send({
            from: 'Analytics Report <onboarding@resend.dev>',
            to: session.user.email,
            subject: `Your ${filename.endsWith('.csv') ? 'CSV Data' : 'PDF Report'} - Helpful Analytics`,
            html: `
                <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #f59e0b;">Analytics Insight Ready</h2>
                    <p>Hello,</p>
                    <p>Attached is your requested analytics dashboard export (<b>${filename}</b>).</p>
                    <p>This report includes the metrics and AI-powered insights generated from your dashboard.</p>
                    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
                    <footer style="font-size: 12px; color: #666;">
                        Generated by Helpful Analytics Engine.
                    </footer>
                </div>
            `,
            attachments: [
                {
                    filename,
                    content: buffer,
                },
            ],
        });

        if (data.error) {
            return NextResponse.json({ error: data.error.message }, { status: 400 });
        }

        return NextResponse.json({ success: true });
    } catch (error) {
        console.error('Email sending failed:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
